### ISSUE TITLE
Do we need this repo?

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-essentials#1] opened 2017-03-03 10:59 UTC
I don't see much purpose and benefit for presets:

 * We have builds as the current way to solve this problem. 
 * If we ever add or remove something from a preset, people will get surprised that suddenly things change within their editors.
 * If it is not solving any serious issue, there is little to no benefit with it.

**Comment by Reinmar** [comment] 2017-03-03 11:01
> We have builds as the current way to solve this problem.

Builds force you to use a certain creator and a precise set of features. And they are not reusable. You can't compose many builds.

> If we ever add or remove something from a preset, people will get surprised that suddenly things change within their editors.

The same is true for builds.

> If it is not solving any serious issue, there is little to no benefit with it.

There's need for presets. Simplifying the work needed to create an editor with all the essentials features.

**Comment by fredck** [comment] 2017-03-03 11:02
If this is just about Clipboard, Enter, Paragraph, Typing, Undo, etc.... let's then create a plugin called "Essentials" and the problem is solved. Let's just not overcomplicate things.

**Comment by Reinmar** [comment] 2017-03-03 11:14
The problem is also solved now and it's solved better. Believe me, you're not creating editors every day. We are. I have enough of updating package.json's with missing deps and importing 10 features to have some reasonable editor for tests.

**Comment by fredck** [comment] 2017-03-03 11:14
> > If we ever add or remove something from a preset, people will get surprised that suddenly things change within their editors.

> The same is true for builds.

That's true as long as you don't create your own build. The problem is when I create my own build and use a preset there.

**Comment by fredck** [comment] 2017-03-03 11:18
> Believe me, you're not creating editors every day. We are.

Make it a dev tool then, just for you. Developers out there are not creating editor every day, but when they do it they want to be sure that things will be under their control.

Btw, what I've [proposed in a previous comment](https://github.com/ckeditor/ckeditor5-presets/issues/1#issuecomment-283926717) seems reasonable.

**Comment by Reinmar** [comment] 2017-03-03 11:21
We'll see. We don't need to promote presets initially, but I think that not sharing such a useful tool is a waste of energy.

Anyway, I plan to keep this package. Even if it's useful only for us. That's already enough.

**Comment by fredck** [comment] 2017-08-31 11:06
I renew my proposal to remove this repository, making the following changes:

 * Move the essentials plugin to `ckeditor5-essentials`.
 * Move the article plugin bundle, which seems to be used only inside tests, to an existing development-only repository, like `ckeditor5`. Optionally, it could have also it's own repo (like `ckeditor5-dev-articlebundle`, if it'll not find fit in existing repos.

This proposal is motivated by a recent talk with @wwalc, when it has been raised the confusion of the name "presets" with the current concept of presets used in CKEditor 4. This additional problem can be added to the list of issues that I've pointed in my initial post here.

**Comment by Reinmar** [comment] 2017-08-31 12:15
The article preset could land in `ckeditor5-core/tests/_utils/` or something. I wouldn't like to add it to `ckeditor5` because it's not a real package and because all other packages would need to have it in their devdeps. 

I'm fine with `ckeditor5-essentials` if you both don't want the presets concept to exist (I agree that it may be too many concepts since we have builds and packages and stuff already). However, at some point, we'll need to address the issue with "which plugins do I need to enable to have that document editor setup?". We'll be talking here about 30+ plugins so it will be easy to miss something. That's the problem I wanted to resolve and I didn't imagine it because it existed in CKE4.

**Comment by fredck** [comment] 2017-08-31 12:34
> "which plugins do I need to enable to have that document editor setup?"

My hope is that specific builds for such setups will help to answer this. Let's wait for the problem to be raised to think what's the right approach.

**Comment by Reinmar** [comment] 2017-09-06 15:52
Just one thing – I'm going to move `ArticlePreset` to `ckeditor5-core`. However, it's now used in the docs – as a way allowing us to quickly create examples there without the need to import a dozen of plugins. There's no way to avoid that, so if anyone will look into the source of these examples, they will see the preset being used.

So, I'm also thinking about naming this `StandardArticlePluginSet`. Or something like this. To make the name as clear as possible.

**Comment by wwalc** [comment] 2017-09-06 16:12
For me it's fine to rename it to `ArticlePluginSet`. "Standard" prefix does not bring any additional semantic value I guess? Beside being a bit confusing due to the "Standard" preset in CKEditor 4?
👍 for changing XXXPreset into more meaningful XXXPluginSet.

**Comment by fredck** [comment] 2017-09-07 13:04
> I'm going to move ArticlePreset to ckeditor5-core.

:?

Right now, `ckeditor5-core` doesn't have any dependency on other packages. Shouldn't this be included into `ckeditor5` instead, which already has all packages available?

**Comment by Reinmar** [comment] 2017-09-07 14:20
> Right now, ckeditor5-core doesn't have any dependency on other packages. Shouldn't this be included into ckeditor5 instead, which already has all packages available?

I explained why not `ckeditor5` above:

> I wouldn't like to add it to ckeditor5 because it's not a real package and because all other packages would need to have it in their devdeps.

It's not ideal to have nearly all packages as devdeps of `ckeditor5-core` too, but it's better this way. The third option is to have a special package for that (like ckeditor5-presets ;)).

**Comment by fredck** [comment] 2017-09-08 07:15
This is just a development tool. As long as it is not messing up with the core package (like adding lots of deps in package.json), it can even be there. If it'll be messy though, then better to find a development dedicated place for it...  like `ckeditor5-dev` or something.

**Comment by Reinmar** [comment] 2017-09-08 11:06
Closed by 7e5e82b.

**Closed by Reinmar** 2017-09-08 11:06 UTC
Labels: candidate:1.0.0, status:confirmed, type:task
